compressionLevel: mixed

enableConstraintsChecks: true

enableGlobalCache: false

enableMirror: true

enableTelemetry: false

enableTransparentWorkspaces: false

injectEnvironmentFiles:
  - .env.yarn?
  - .env.local?

nodeLinker: node-modules

npmPublishRegistry: "https://registry.npmjs.org"

plugins:
  - checksum: e42f11830198f5cbeb2cf2c64350dd93bafad27863575b8a7493aecd2703cf3d01bf76e51b6959329fc8fef785aed8a5dd255d121c43d1c7fa0d11f9b0cda969
    path: .yarn/plugins/yarn-plugin-echoscript.cjs
    spec: "https://raw.githubusercontent.com/taeyoon0137/echoscript/main/packages/plugin/plugin/bundle.js"

progressBarStyle: jack

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  os:
    - current
    - linux
    - darwin

yarnPath: .yarn/releases/yarn-4.0.2.cjs
